---
- name: uninstall build deps
  shell: >
    apk del flightdeck-build
- name: clear caches
  shell: >
    rm -rf {{ item }}
  args:
    warn: no
  loop:
    - "/tmp/*"
    - "/var/cache/apk/*"
    - "/var/www/.composer/cache"
    - "/var/www/.npm/_cacache"
    - "/root/.ansible/tmp"
    - "/root/.cache"
